version: '3.8'
services:
    hello:
        build: .
        container_name: hello
        depends_on:
            - 'mongo'
            - 'postgres'
        environment:
            - PORT=3000
        ports:
            - '3000:3000'
        volumes:
            - './:/app'
        stdin_open: true
        tty: true
    mongo:
        image: 'mongo:latest'
        container_name: mongo
        ports:
            - '27017:27017'
        volumes:
            - ./mongodata:/data/db
        restart: always
    mongo_express:
        image: 'mongo-express:latest'
        container_name: mongo_express
        depends_on:
            - 'mongo'
        ports:
            - '8081:8081'
        restart: always
    postgres:
        image: postgres:latest
        restart: always
        environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=hello
        ports:
        - '5432:5432'
        volumes: 
        - postgresdb:/var/lib/postgresql/data
        stdin_open: true
        tty: true
    pgadmin:
        container_name: pgadmin
        image: dpage/pgadmin4:latest
        environment:
            PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
            PGADMIN_DEFAULT_PASSWORD: admin
        volumes:
        - pgadmin:/root/.pgadmin
        ports:
        - "8082:80"
        depends_on:
            - 'postgres'
        restart: always
volumes:
  postgresdb:
    driver: local
  pgadmin:
    driver: local