apiVersion: v1
kind: Service
metadata:
  name: hello-cicd
spec:
  type: LoadBalancer
  selector:
    app: hello-cicd
  ports:
  - port: 8081
    name: http
    targetPort: 8081
  - port: 8082
    name: grpc
    targetPort: 8082